name:                 game-frontend
version:              0.1.0.0
visibility:           public
id:                   game-frontend-0.1.0.0-5EIZgYS0iBaCOPxQxBiA2w
key:                  game-frontend-0.1.0.0-5EIZgYS0iBaCOPxQxBiA2w
license:              MIT
maintainer:           dev@example.com
author:               Developer
synopsis:             A Haskell Game Frontend using Gloss
description:          Multiplayer game frontend built with the Gloss library
abi:                  e24190b95317aba9928d456a40f70067
exposed:              True
exposed-modules:
    AssetLoader GameLogic Input NetworkClient Render.Core Render.Map
    Render.UI Types

hidden-modules:       Paths_game_frontend
import-dirs:
    D:\game-frontend\.stack-work\install\1eee3797\lib\x86_64-windows-ghc-9.4.8\game-frontend-0.1.0.0-5EIZgYS0iBaCOPxQxBiA2w

library-dirs:
    D:\game-frontend\.stack-work\install\1eee3797\lib\x86_64-windows-ghc-9.4.8\game-frontend-0.1.0.0-5EIZgYS0iBaCOPxQxBiA2w
    C:\Users\gamat\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\lib
    C:\Users\gamat\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\bin

library-dirs-static:
    D:\game-frontend\.stack-work\install\1eee3797\lib\x86_64-windows-ghc-9.4.8\game-frontend-0.1.0.0-5EIZgYS0iBaCOPxQxBiA2w
    C:\Users\gamat\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\lib
    C:\Users\gamat\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\bin

dynamic-library-dirs:
    D:\game-frontend\.stack-work\install\1eee3797\lib\x86_64-windows-ghc-9.4.8
    C:\Users\gamat\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\lib
    C:\Users\gamat\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\bin

data-dir:
    D:\game-frontend\.stack-work\install\1eee3797\share\x86_64-windows-ghc-9.4.8\game-frontend-0.1.0.0

hs-libraries:         HSgame-frontend-0.1.0.0-5EIZgYS0iBaCOPxQxBiA2w
include-dirs:
    C:\Users\gamat\AppData\Local\Programs\stack\x86_64-windows\msys2-20240727\clang64\include

depends:
    base-4.17.2.1 bytestring-0.11.5.3 containers-0.6.7
    gloss-1.13.2.2-A0pcjDq0q2uC7L4VMwXRN1
    network-3.1.4.0-4w491xmGmp0DHdxuiVhuD8 stm-2.5.1.0

haddock-interfaces:
    D:\game-frontend\.stack-work\install\1eee3797\doc\game-frontend-0.1.0.0\game-frontend.haddock

haddock-html:
    D:\game-frontend\.stack-work\install\1eee3797\doc\game-frontend-0.1.0.0
